"""Quantitative analyst briefs — what to ask, variables, math, and approach per problem type."""

ANALYST_BRIEFS: dict[str, dict] = {
    "betting": {
        "type_label": "Betting / poker decision",
        "what_is_asked": "Does this wager have **positive expected value** over many similar decisions?",
        "variables": "Win probability, pot size, bet/call amount, stack size, rake",
        "math_useful": "Probability, expected value, pot odds, bankroll sizing",
        "analyst_steps": [
            "Estimate your win probability (equity) for this decision.",
            "Convert pot odds to the break-even probability required to call.",
            "Compute expected value: EV = P(win)×gain − P(lose)×loss.",
            "Size the bet so variance does not threaten long-run survival.",
        ],
        "limitations": "Single-hand results are noisy — judge decision quality over hundreds of hands.",
        "math_behind": {
            "Probability": "Equity = P(win) given cards and opponent ranges.",
            "Expected value": "EV = Σ P(outcome) × payoff — positive EV means profitable long-term.",
            "Optimization": "Kelly criterion sizes bets to maximize long-run growth subject to ruin risk.",
        },
        "interactive": "ev_bet",
    },
    "sports": {
        "type_label": "Sports prediction / wagering",
        "what_is_asked": "Is your estimated win probability **higher than the market's implied probability**?",
        "variables": "Team strength, injuries, home field, sample size, odds, bet size",
        "math_useful": "Statistics, probability, expected value, regression to the mean",
        "analyst_steps": [
            "Estimate true win probability from data (ratings, injuries, context).",
            "Convert betting odds to implied probability.",
            "Calculate expected value per dollar wagered.",
            "Report uncertainty — wide intervals on small samples.",
        ],
        "limitations": "Past performance blends skill and luck; shrink extreme records toward average.",
        "math_behind": {
            "Statistics": "Shrinkage estimators pull extreme stats toward the league mean.",
            "Probability": "Implied probability from odds: for +150, implied ≈ 100/(150+100) = 40%.",
            "Expected value": "EV = p×(profit if win) − (1−p)×(stake if lose).",
        },
        "interactive": "ev_bet",
    },
    "medicine": {
        "type_label": "Treatment / disease modeling",
        "what_is_asked": "Does the treatment **change the outcome vs. a control**, and at what cost in toxicity?",
        "variables": "Tumor volume, growth rate, kill rate, dose, survival time, side-effect rate",
        "math_useful": "Calculus (rates), statistics (trials), differential equations, optimization",
        "analyst_steps": [
            "Define the outcome (survival, shrinkage, biomarker).",
            "Identify variables: growth rate vs. treatment kill rate.",
            "Require a control group — compare treatment to no treatment or standard care.",
            "State limitations: patient heterogeneity, trial size, follow-up time.",
        ],
        "limitations": "Response rate without control does not prove causation.",
        "math_behind": {
            "Calculus": "dV/dt = growth rate − treatment kill rate models tumor volume over time.",
            "Statistics": "Hazard ratios and survival curves compare treatment vs. control.",
            "Optimization": "Dose optimization trades efficacy against toxicity constraints.",
        },
        "interactive": "growth",
    },
    "ai": {
        "type_label": "Machine learning / prediction model",
        "what_is_asked": "Will this model **predict well on new data**, not just training data?",
        "variables": "Features, labels, loss, parameters, train/validation/test metrics",
        "math_useful": "Optimization (gradients), statistics, probability, regularization",
        "analyst_steps": [
            "Define the objective (loss) you are minimizing.",
            "Split data: train, validate, test — never tune on test.",
            "Track validation error while training; stop before overfitting.",
            "Report test performance once, with confidence intervals if possible.",
        ],
        "limitations": "High training accuracy often means memorization, not learning.",
        "math_behind": {
            "Optimization": "Gradient descent updates weights to minimize loss: w ← w − η∇L.",
            "Statistics": "Bias-variance tradeoff: complex models fit noise; simple models underfit.",
            "Probability": "Calibration — predicted probabilities should match observed frequencies.",
        },
        "interactive": "ml_split",
    },
    "business": {
        "type_label": "Business / strategy quant question",
        "what_is_asked": "Which lever **most moves the metric** (profit, conversion, LTV) per unit of spend?",
        "variables": "Conversion, CAC, LTV, price, cost, capacity, demand",
        "math_useful": "Statistics (A/B tests), optimization, forecasting, unit economics",
        "analyst_steps": [
            "Write the metric as a function of levers (e.g. profit = revenue − cost).",
            "Identify the binding constraint (budget, capacity, demand).",
            "Run a controlled experiment or cohort analysis before scaling.",
            "Forecast with scenarios, not a single point estimate.",
        ],
        "limitations": "Correlation in historical data is not causation.",
        "math_behind": {
            "Statistics": "A/B tests estimate causal lift with confidence intervals.",
            "Optimization": "Maximize objective subject to budget and capacity constraints.",
            "Probability": "Forecast ranges account for demand uncertainty.",
        },
        "interactive": "unit_econ",
    },
    "traffic": {
        "type_label": "Traffic / operations optimization",
        "what_is_asked": "How do we **minimize delay** (or cost) subject to capacity and safety?",
        "variables": "Flow rate, capacity, demand, signal timing, route choice",
        "math_useful": "Optimization, simulation, queueing theory, statistics",
        "analyst_steps": [
            "Model demand vs. capacity — where is the bottleneck?",
            "Simulate interventions (signals, lanes, pricing) before deploying.",
            "Check for induced demand — fixing one bottleneck may shift congestion.",
            "Measure average travel time and variance, not single trips.",
        ],
        "limitations": "Static models miss accidents and demand spikes.",
        "math_behind": {
            "Optimization": "Minimize average travel time subject to capacity constraints.",
            "Simulation": "Monte Carlo runs many demand scenarios to estimate delay distributions.",
            "Calculus": "Flow conservation links entry rate, exit rate, and queue buildup.",
        },
        "interactive": "queue",
    },
    "engineering": {
        "type_label": "Engineering / design optimization",
        "what_is_asked": "What design **maximizes performance per cost** within physical and safety limits?",
        "variables": "Efficiency, dimensions, materials, speed, cost, failure rate",
        "math_useful": "Calculus, optimization, simulation, tolerance analysis",
        "analyst_steps": [
            "List constraints (physics, safety, budget) before optimizing.",
            "Build a simple model linking inputs to performance.",
            "Prototype and measure — compare model prediction to data.",
            "Add safety margins for unknown operating conditions.",
        ],
        "limitations": "Lab conditions may not match field performance.",
        "math_behind": {
            "Calculus": "Derivatives find where performance changes fastest with a design parameter.",
            "Optimization": "Maximize output/cost subject to stress and safety constraints.",
            "Simulation": "Finite-element models stress-test designs before building.",
        },
        "interactive": "tradeoff",
    },
    "weather": {
        "type_label": "Weather / forecast quant question",
        "what_is_asked": "What is the **probability distribution** of outcomes, and how does uncertainty grow with lead time?",
        "variables": "Initial conditions, ensemble members, lead time, region",
        "math_useful": "Statistics, probability, simulation, chaos-sensitive dynamics",
        "analyst_steps": [
            "Use ensemble forecasts — many model runs, not one deterministic track.",
            "Report calibrated probabilities (e.g. 30% chance of rain means ~30% of such days rain).",
            "Widen uncertainty intervals as lead time increases.",
            "Compare models to observations to score calibration.",
        ],
        "limitations": "Small errors in initial conditions grow — long-range detail is unreliable.",
        "math_behind": {
            "Probability": "Ensemble spread approximates forecast uncertainty.",
            "Statistics": "Brier score measures calibration of probabilistic forecasts.",
            "Simulation": "Numerical weather models integrate fluid dynamics forward in time.",
        },
        "interactive": "forecast",
    },
    "default": {
        "type_label": "Quantitative decision / prediction",
        "what_is_asked": "What quantity are you **estimating, comparing, or optimizing** — and how will you know if you're right?",
        "variables": "Outcome, inputs you control, external factors, measurement error",
        "math_useful": "Statistics, probability, optimization — pick tools that match the question",
        "analyst_steps": [
            "State the question as a measurable quantity.",
            "List variables: decisions vs. observations vs. unknowns.",
            "Choose math that fits (EV for bets, regression for trends, optimization for constraints).",
            "Define one test that would falsify your answer.",
        ],
        "limitations": "Vague questions produce vague models — sharpen before calculating.",
        "math_behind": {
            "Probability": "Quantify uncertainty with distributions, not point guesses.",
            "Statistics": "Use data to estimate parameters and confidence intervals.",
            "Optimization": "Find the best feasible choice given constraints.",
        },
        "interactive": "ev_bet",
    },
}
