"""Professional case studies keyed by identifier."""

CASE_STUDIES: dict[str, dict] = {
    "finance_black_scholes": {
        "title": "Black–Scholes and the invention of tradable risk",
        "setting": "Options desk, investment bank, 1973 onward",
        "problem": "How do you price a derivative on a stock whose future is random but not arbitrary?",
        "approach": "Geometric Brownian motion for the underlying, delta-hedging eliminates risk in continuous time, PDE → closed-form call price.",
        "methods": ["Stochastic calculus (Itô)", "Partial differential equations", "Risk-neutral pricing"],
        "impact": "Created a liquid options market; reframed volatility as a tradable quantity; foundation for modern derivatives desks.",
        "lesson": "A seemingly pure math formula became industrial infrastructure for global finance.",
    },
    "finance_2008_crisis": {
        "title": "2008 — when correlation went to one",
        "setting": "Risk management, mortgage-backed securities, global banks",
        "problem": "Models assumed diversification across tranches; systemic housing decline broke independence assumptions.",
        "approach": "Gaussian copula on MBS defaults; underestimated tail dependence and liquidity spirals.",
        "methods": ["Copulas", "VaR", "Monte Carlo stress (underweighted)"],
        "impact": "Demonstrated that tail risk and funding liquidity dominate mean-variance intuition.",
        "lesson": "Simulation must stress **joint extremes**, not only marginal distributions.",
    },
    "medicine_clinical_trial": {
        "title": "Randomized oncology trial — is the effect real?",
        "setting": "Phase III trial comparing Treatment A vs standard of care",
        "problem": "Tumor shrinkage observed — but could it be chance in 200 patients?",
        "approach": "Intent-to-treat analysis, Kaplan–Meier survival, hazard ratio with confidence interval, pre-registered stopping rules.",
        "methods": ["Survival analysis", "Hypothesis testing", "Bayesian optional interim looks"],
        "impact": "Regulatory approval requires quantified uncertainty, not anecdotal response.",
        "lesson": "Statistics is the gatekeeper between biological signal and clinical action.",
    },
    "medicine_tumor_competing_rates": {
        "title": "Personalized treatment — competing growth rates",
        "setting": "Medical oncology clinic",
        "problem": "Patient tumor growing at 8%/month; therapy estimated to reduce net rate by 6%.",
        "approach": "Exponential growth model with treatment term; simulate scenarios for adherence and resistance.",
        "methods": ["ODE growth models", "Pharmacokinetic exposure linking", "Uncertainty on patient-specific k"],
        "impact": "Informs whether expected net rate is negative before imaging confirms response.",
        "lesson": "Calculus compares rates, not single snapshots.",
    },
    "ai_llm_training": {
        "title": "Training a large language model",
        "setting": "Foundation model pretraining cluster",
        "problem": "Predict next token across trillions of tokens with stable optimization at scale.",
        "approach": "Transformer architecture, cross-entropy loss, AdamW optimizer, learning-rate warmup and decay, checkpoint on validation perplexity.",
        "methods": ["Gradient descent", "Backpropagation", "Regularization", "Distributed data parallelism"],
        "impact": "Enables general-purpose reasoning interfaces; loss curves and eval harness are production metrics.",
        "lesson": "AI training is industrial optimization with statistical generalization constraints.",
    },
    "ai_calibration": {
        "title": "Prediction confidence in medical AI",
        "setting": "Radiology triage model deployment",
        "problem": "Model accuracy 92% but hides overconfidence on rare cancers.",
        "approach": "Calibration plots, temperature scaling, human-in-the-loop thresholds by cost asymmetry.",
        "methods": ["Probabilistic outputs", "ROC vs calibration", "Conformal prediction (advanced)"],
        "impact": "Hospitals set operating points on **expected harm**, not accuracy alone.",
        "lesson": "Probability must be **calibrated** to support decisions.",
    },
    "sports_moneyball": {
        "title": "Moneyball — market inefficiency via statistics",
        "setting": "Oakland Athletics front office, early 2000s",
        "problem": "Compete against teams with 3× payroll.",
        "approach": "Value players by on-base percentage and undervalued metrics; shrink noisy performance toward true talent.",
        "methods": ["Regression", "Empirical Bayes shrinkage", "Linear programming for roster constraints"],
        "impact": "Changed baseball scouting; spread to basketball, soccer, and hiring analogies.",
        "lesson": "Better measurement beats bigger budgets when markets misprice signal.",
    },
    "sports_win_probability": {
        "title": "In-game win probability models",
        "setting": "NBA fourth-quarter decision desk",
        "problem": "Should the team foul late, or defend the three?",
        "approach": "Logistic model from score differential, time, possession, home court; updated play-by-play.",
        "methods": ["Logistic regression", "Markov possession models", "Monte Carlo remainder simulation"],
        "impact": "Coaches and broadcasters use live WP; fan engagement product.",
        "lesson": "Real-time prediction merges statistics with operations research.",
    },
    "epidemiology_covid_policy": {
        "title": "COVID-19 — R₀, R_t, and policy timing",
        "setting": "Public health agency scenario room",
        "problem": "When do hospitalizations peak if contact rates drop 30% in two weeks vs six?",
        "approach": "SEIR compartment models, time-varying β(t), ensemble parameter uncertainty.",
        "methods": ["ODE epidemiology", "Bayesian nowcasting", "Agent-based supplements"],
        "impact": "Informed lockdown timing, vaccination prioritization, and surge staffing.",
        "lesson": "Small delays in intervention shift peak burden nonlinearly.",
    },
    "crypto_tls": {
        "title": "TLS handshake securing the web",
        "setting": "Browser connecting to a bank website",
        "problem": "Establish encrypted channel resistant to eavesdropping and tampering.",
        "approach": "RSA or elliptic-curve Diffie–Hellman key exchange, symmetric AES session, certificate chain signed by trusted CA.",
        "methods": ["Modular arithmetic", "Elliptic curves", "Hash functions"],
        "impact": "E-commerce and cloud APIs depend on this mathematical stack billions of times per day.",
        "lesson": "Number theory is load-bearing infrastructure, not abstract curiosity.",
    },
    "astronomy_exoplanet": {
        "title": "Kepler mission — transits at scale",
        "setting": "NASA exoplanet survey, 2009–2018",
        "problem": "Detect Earth-size planets trillions of miles away from periodic dimming.",
        "approach": "High-precision photometry; search for periodic transit signals; rule out stellar variability false positives.",
        "methods": ["Fourier/periodogram search", "Bayesian parameter fitting", "Noise modeling"],
        "impact": "Confirmed thousands of exoplanets; reframed habitable-zone statistics.",
        "lesson": "Tiny periodic signals in noise require statistical detection theory.",
    },
    "weather_hurricane_cone": {
        "title": "Hurricane forecast cone",
        "setting": "National Hurricane Center advisory",
        "problem": "Communicate track uncertainty without false precision.",
        "approach": "Ensemble of physics-based and statistical tracks; cone contains 60–70% of historical errors.",
        "methods": ["Numerical weather prediction", "Ensemble spread", "Calibration of track errors"],
        "impact": "Evacuation decisions use cone width, not a single line.",
        "lesson": "Professional forecasting is probabilistic geometry, not a single path.",
    },
    "climate_paris": {
        "title": "Paris Agreement — cumulative carbon and temperature",
        "setting": "IPCC policy scenarios",
        "problem": "Link emissions pathways to likely warming bands by 2100.",
        "approach": "Simple climate models + full GCM ensembles; carbon budget from integrated emissions.",
        "methods": ["Energy balance models", "Ensemble climate projection", "Uncertainty bands"],
        "impact": "National commitments framed around 1.5°C / 2°C guardrails.",
        "lesson": "Policy uses scenario **distributions**, not deterministic prophecy.",
    },
}
