"""Backward-compatible re-exports."""

from content.practical_labs import (
    ACTION_LABELS,
    ACTION_TO_LAB,
    NUM_PRACTICAL_LABS,
    PRACTICAL_LABS,
    PRACTICAL_LAB_NAMES,
)

LAB_NAMES = PRACTICAL_LAB_NAMES
INTERACTIVE_LABS = PRACTICAL_LABS
NUM_LABS = NUM_PRACTICAL_LABS
