"""Portfolio Lab — interview-grade project specifications."""

PORTFOLIO_PROBLEMS = [
    {
        "title": "Tail-Risk Dashboard for Multi-Asset Portfolio",
        "domain": "Quantitative Finance",
        "systems": "Probability · Simulation · Optimization",
        "question": "How much capital is at risk in the worst 5% of simulated years for a correlated stock/bond portfolio?",
        "data_needed": "Daily or monthly adjusted close for 3–5 ETFs (e.g. SPY, TLT, GLD); optional VIX. Source: yfinance CSV export.",
        "excel": "Build 2,000 simulation rows with correlated NORM.INV(RAND()) shocks; columns for annual return, terminal wealth, max drawdown; summarize percentiles.",
        "python": "pandas + numpy multivariate normal paths; plot terminal wealth histogram, fan chart, and drawdown series; compute VaR/CVaR.",
        "methods": ["Monte Carlo", "Cholesky correlation", "Drawdown path analytics", "Portfolio variance"],
        "visualizations": ["Terminal wealth histogram", "Drawdown underwater chart", "Correlation heatmap"],
        "interview": "Explain why 2008 broke Gaussian copula assumptions; how you would stress correlation → 1 in crisis.",
        "github_readme": "Quant portfolio tail-risk engine with reproducible simulations and risk metrics for interview discussion.",
    },
    {
        "title": "SIR Intervention Timing & Hospital Surge",
        "domain": "Epidemiology",
        "systems": "Calculus · Simulation",
        "question": "How many days earlier must contact reduction occur to cut peak hospitalizations by 25%?",
        "data_needed": "Public case series (date, cases, hospitalizations) from CDC or OWID CSV.",
        "excel": "Discrete-time SIR with β, γ, N; scenario table for intervention start day; chart infectious compartment.",
        "python": "scipy.integrate.odeint or discrete SIR; overlay observed cases; sensitivity heatmap on β and intervention delay.",
        "methods": ["Compartment ODEs", "R₀ / R_t", "Scenario comparison", "Peak timing sensitivity"],
        "visualizations": ["SIR stack plot", "Peak vs intervention day curve", "Observed vs modeled fit"],
        "interview": "Discuss structural model limits (homogeneous mixing) and why R_t is the operational metric.",
        "github_readme": "Epidemic scenario tool comparing policy timing on hospital surge — links math to public-health decisions.",
    },
    {
        "title": "Moneyball Shrinkage Projection System",
        "domain": "Sports Analytics",
        "systems": "Statistics · Bayesian thinking",
        "question": "What is a player's true talent after 30 games if career rate is 22 and current season is 31?",
        "data_needed": "Player-season CSV: player, season, games, rate stat (OBP, points per game, etc.).",
        "excel": "Weighted blend w = n_career / (n_career + n_season); projection column; error bars from SE formula.",
        "python": "Empirical Bayes or PyMC partial pooling; plot prior, likelihood, posterior; backtest holdout seasons.",
        "methods": ["Shrinkage / partial pooling", "Regression to the mean", "Out-of-sample RMSE"],
        "visualizations": ["Prior–posterior bar chart", "Projection vs actual scatter", "Shrinkage weight by sample size"],
        "interview": "Why raw season stats overpay free agents; how shrinkage changes roster decisions.",
        "github_readme": "Sports projection model demonstrating professional-grade talent estimation under noise.",
    },
    {
        "title": "Neural Training Diagnostics & Generalization Gap",
        "domain": "Machine Learning",
        "systems": "Optimization · Statistics · AI",
        "question": "At which epoch does validation loss diverge from training loss for this architecture?",
        "data_needed": "Tabular or image dataset (sklearn digits, MNIST subset, or Kaggle tabular).",
        "excel": "Log epoch, train_loss, val_loss, val_accuracy in sheets; line chart divergence point.",
        "python": "PyTorch or sklearn MLP; early stopping; learning curves; confusion matrix on holdout.",
        "methods": ["Cross-entropy loss", "Gradient descent", "Train/val split", "Regularization"],
        "visualizations": ["Learning curve dual plot", "Confusion matrix", "Calibration plot"],
        "interview": "Walk through leakage checks, metric choice, and when to stop training.",
        "github_readme": "ML training audit notebook showing optimization dynamics and generalization monitoring.",
    },
    {
        "title": "Election Forecast Calibration Report",
        "domain": "Election Forecasting",
        "systems": "Probability · Statistics · Simulation",
        "question": "When the model says 70%, do candidates win ~70% historically (calibration)?",
        "data_needed": "Historical forecasts + outcomes, or state polls with dates from open 538-style files.",
        "excel": "Bin predictions into deciles; compute win rate per bin; Brier score formula.",
        "python": "Simulate electoral college from state win probs; reliability diagram; Brier vs baseline.",
        "methods": ["Bernoulli outcomes", "Brier score", "Calibration curves", "Monte Carlo aggregation"],
        "visualizations": ["Reliability diagram", "Forecast vs outcome scatter", "EV distribution histogram"],
        "interview": "Defend probabilistic forecasts against media certainty; discuss correlated state errors.",
        "github_readme": "Forecast evaluation harness proving statistical honesty in probabilistic election modeling.",
    },
    {
        "title": "Pharmacokinetic Dosing & Exposure (AUC) Analysis",
        "domain": "Drug Development",
        "systems": "Calculus",
        "question": "Which dosing schedule keeps concentration inside the therapeutic window?",
        "data_needed": "Synthetic or literature PK parameters: dose, k_elim, V_d (optional).",
        "excel": "Hourly concentration recursion; shade min effective and max toxic thresholds.",
        "python": "One-compartment ODE with scipy.integrate; Monte Carlo on clearance; AUC with np.trapezoid.",
        "methods": ["Exponential decay ODE", "AUC exposure", "Steady-state superposition"],
        "visualizations": ["Concentration–time curve", "Therapeutic window shading", "Parameter sensitivity"],
        "interview": "Link AUC to efficacy/toxicity endpoints; role of variability in Phase I design.",
        "github_readme": "Clinical PK explorer connecting calculus to dosing decisions in drug development.",
    },
    {
        "title": "Poker Bankroll & Kelly Sizing Study",
        "domain": "Gambling & Poker",
        "systems": "Probability",
        "question": "What fraction of bankroll maximizes long-run growth without unacceptable ruin risk?",
        "data_needed": "Hand-history EV estimates or synthetic win rate, pot size, rake.",
        "excel": "EV per hand; simulate 500 sessions with fixed vs Kelly fraction bet sizing.",
        "python": "Monte Carlo 10,000 careers; plot wealth paths; estimate risk of ruin vs Kelly fraction.",
        "methods": ["Expected value", "Kelly criterion", "Risk of ruin", "Variance of returns"],
        "visualizations": ["Bankroll path fan chart", "Ruin probability vs bet fraction", "EV sensitivity"],
        "interview": "Why positive EV does not guarantee short-run profit; tradeoff growth vs variance.",
        "github_readme": "Decision mathematics demo for poker / trading bankroll management under uncertainty.",
    },
    {
        "title": "Climate Scenario Ensemble Brief",
        "domain": "Climate Modeling",
        "systems": "Calculus · Simulation",
        "question": "How wide is the 2100 temperature band across low vs high emission scenarios?",
        "data_needed": "NASA GISTEMP or NOAA anomaly CSV; optional CMIP scenario parameters.",
        "excel": "Energy-balance box model with scenario forcing slider; table of anomaly by decade.",
        "python": "Ensemble of 100 runs per scenario; fan chart; sensitivity to feedback parameter.",
        "methods": ["Energy balance ODE", "Scenario analysis", "Ensemble uncertainty"],
        "visualizations": ["Scenario fan chart", "Forcing vs anomaly plot", "Parameter sensitivity tornado"],
        "interview": "Separate epistemic vs scenario uncertainty; communication to non-technical stakeholders.",
        "github_readme": "Climate scenario laboratory articulating policy pathways as distributions, not single lines.",
    },
    {
        "title": "Exoplanet Transit Detection Pipeline (Toy)",
        "domain": "Astronomy & Astrophysics",
        "systems": "Statistics · Signal processing",
        "question": "Can you detect a periodic dimming signal buried in noise (transit)?",
        "data_needed": "Kepler light-curve sample or synthetic flux series (time, flux, error).",
        "excel": "Moving average smooth; periodogram peak search (coarse).",
        "python": "Inject synthetic transit; Lomb-Scargle or FFT peak; SNR vs depth plot.",
        "methods": ["Periodogram", "Noise modeling", "Detection SNR", "Parameter fitting"],
        "visualizations": ["Light curve with transit", "Periodogram peak", "Residuals after fit"],
        "interview": "False positive vetting; why space-based photometry revolutionized planet counts.",
        "github_readme": "Astronomy signal-detection mini-pipeline mirroring professional transit surveys.",
    },
    {
        "title": "Recommendation Ranker Offline Evaluation",
        "domain": "Internet Recommendation Systems",
        "systems": "Statistics · AI · Optimization",
        "question": "Does a new ranking function beat baseline on precision@10 without popularity bias?",
        "data_needed": "Movielens 100k or implicit feedback matrix (user, item, rating/timestamp).",
        "excel": "Pivot user-item matrix; cosine similarity on small subset.",
        "python": "Train/test split; matrix factorization or implicit ALS; NDCG@10, coverage metric.",
        "methods": ["Collaborative filtering", "Ranking metrics", "Train/holdout protocol", "Popularity debiasing"],
        "visualizations": ["Precision@k curve", "Popularity histogram of recommendations", "Latent space PCA"],
        "interview": "Offline vs online metrics; exploration/exploitation in production.",
        "github_readme": "Recommender evaluation report with defensible offline protocol for product analytics interviews.",
    },
    {
        "title": "Actuarial Aggregate Loss & Capital Layer",
        "domain": "Actuarial Science",
        "systems": "Probability · Simulation",
        "question": "What 99.5th percentile annual loss requires capital reserves?",
        "data_needed": "Synthetic claim frequency/severity or NAIC-style aggregated loss triangles (public reports).",
        "excel": "Simulate Poisson claim counts × lognormal severities; percentile table.",
        "python": "10k year simulation; VaR/TVaR; layer reinsurance strip on tail.",
        "methods": ["Compound distributions", "Monte Carlo", "TVaR", "Reinsurance layering"],
        "visualizations": ["Aggregate loss histogram", "Exceedance probability curve", "Capital layer diagram"],
        "interview": "Solvency II / risk-based capital intuition; difference between expected loss and tail capital.",
        "github_readme": "Actuarial loss model demonstrating insurer capital thinking under compound uncertainty.",
    },
    {
        "title": "1D Kalman Filter for Tracking & Sensor Fusion",
        "domain": "Autonomous Vehicles",
        "systems": "Probability · Calculus · Linear systems",
        "question": "How do noisy GPS and velocity measurements fuse into a smooth position estimate?",
        "data_needed": "Synthetic time series: true position, GPS noise, IMU velocity noise.",
        "excel": "Not recommended — use Python for state-space clarity.",
        "python": "Implement predict/update Kalman loop; plot true vs raw vs filtered; tune Q/R.",
        "methods": ["State-space model", "Kalman filter", "Process vs measurement noise"],
        "visualizations": ["Position trace comparison", "Innovation residuals", "Covariance shrinkage over time"],
        "interview": "Predict-update intuition; extension to extended Kalman for nonlinear autonomy stacks.",
        "github_readme": "Sensor fusion demo showing probabilistic filtering in autonomous systems context.",
    },
]
