"""Portfolio and interview laboratory problems."""

PORTFOLIO_PROBLEMS = [
    {
        "title": "Quantitative Finance — Tail Risk Dashboard",
        "domain": "Quantitative Finance",
        "systems": "Probability, Simulation, Optimization",
        "prompt": "Build a Monte Carlo engine for a two-asset portfolio with correlation. Report median wealth, 5th percentile, and probability of 20% drawdown.",
        "excel": "Cholesky-style correlated normals via NORM.INV(RAND()) for two assets; 5,000 paths over 25 years.",
        "python": "numpy.random.multivariate_normal; plot fan chart and tail metrics.",
        "interview": "Explain why correlation spikes in crises invalidate static covariance models.",
    },
    {
        "title": "Epidemiology — Intervention Timing",
        "domain": "Epidemiology",
        "systems": "Calculus, Simulation",
        "prompt": "Simulate SIR dynamics under early vs delayed contact reduction. Quantify peak hospitalizations.",
        "excel": "Discrete-time SIR with daily β slider and cumulative cases.",
        "python": "ODE or discrete SIR with matplotlib peak comparison.",
        "interview": "Discuss R₀, R_t, and why exponential early growth dominates public messaging.",
    },
    {
        "title": "Actuarial Science — Capital at Risk",
        "domain": "Actuarial Science",
        "systems": "Probability, Simulation",
        "prompt": "Model annual claims as Poisson frequency × lognormal severity. Estimate 99.5th percentile capital.",
        "excel": "Simulate 2,000 policy years; histogram aggregate loss.",
        "python": "Aggregate loss distribution with scipy.stats; VaR and TVaR.",
        "interview": "Connect tail capital to regulatory solvency thinking.",
    },
    {
        "title": "Sports Analytics — Shrinkage Projections",
        "domain": "Sports Analytics",
        "systems": "Statistics",
        "prompt": "Project player performance using career prior and current season with explicit shrinkage weight.",
        "excel": "Weighted average formula with sample-size-dependent weight.",
        "python": "Bayesian normal model or empirical Bayes shrinkage demo.",
        "interview": "Explain regression to the mean without hand-waving.",
    },
    {
        "title": "Machine Learning — Training Diagnostics",
        "domain": "Machine Learning",
        "systems": "Optimization, Statistics, AI",
        "prompt": "Train a classifier; plot train vs validation error by epoch; document overfitting onset.",
        "excel": "Log epochs, loss, accuracy in tables; chart divergence point.",
        "python": "sklearn + learning_curve; discuss bias-variance.",
        "interview": "Walk through how you would detect leakage and fix it.",
    },
    {
        "title": "Supply Chain — Stockout Risk",
        "domain": "Supply Chain Optimization",
        "systems": "Simulation, Optimization",
        "prompt": "Simulate inventory with stochastic lead times; compare safety stock policies.",
        "excel": "Daily inventory balance with RAND-driven lead times.",
        "python": "Discrete-event simulation; optimize reorder point.",
        "interview": "Frame tradeoff between holding cost and service level.",
    },
    {
        "title": "Election Forecasting — Calibration Study",
        "domain": "Election Forecasting",
        "systems": "Statistics, Probability, Simulation",
        "prompt": "Simulate 500 elections from state-level win probabilities; evaluate calibration of 70% forecasts.",
        "excel": "Electoral vote tally from Bernoulli state draws.",
        "python": "Brier score and reliability diagram on synthetic history.",
        "interview": "Defend probabilistic forecasts vs media certainty narratives.",
    },
    {
        "title": "Drug PK — Dosing Scenario",
        "domain": "Drug Development",
        "systems": "Calculus",
        "prompt": "Model one-compartment elimination; compare Q8h vs Q12h dosing on C_min and C_max.",
        "excel": "Recursive concentration update per dose time.",
        "python": "ODE integration; shade therapeutic window.",
        "interview": "Define AUC and why regulators care about exposure metrics.",
    },
    {
        "title": "Autonomous Systems — Tracking Filter",
        "domain": "Autonomous Vehicles",
        "systems": "Probability, Calculus",
        "prompt": "Implement a 1D Kalman filter tracking position from noisy velocity measurements.",
        "excel": "Not ideal — emphasize Python for state-space.",
        "python": "Kalman filter loop; plot true vs estimated vs noisy.",
        "interview": "Explain predict-update cycle in plain language.",
    },
    {
        "title": "Climate — Policy Sensitivity",
        "domain": "Climate Modeling",
        "systems": "Calculus, Simulation",
        "prompt": "Explore a simple energy balance model across forcing scenarios; report years to +1.5°C anomaly.",
        "excel": "Euler update of temperature anomaly per year.",
        "python": "Parameter ensemble with uncertainty bands.",
        "interview": "Separate model uncertainty from policy uncertainty in communication.",
    },
    {
        "title": "Recommendation Systems — Offline Eval",
        "domain": "Internet Recommendation Systems",
        "systems": "Statistics, AI, Optimization",
        "prompt": "Build a small recommender; evaluate precision@k on holdout users.",
        "excel": "User-item matrix pivot and manual similarity.",
        "python": "Surprise or implicit ALS; NDCG@10 chart.",
        "interview": "Discuss popularity bias and diversity constraints.",
    },
    {
        "title": "Poker Mathematics — Bankroll Survival",
        "domain": "Gambling & Poker",
        "systems": "Probability",
        "prompt": "Simulate sessions with known edge and variance; compare Kelly vs fixed fraction bet sizing.",
        "excel": "EV per hand and cumulative bankroll paths.",
        "python": "Monte Carlo 10,000 careers; risk of ruin curves.",
        "interview": "Explain why positive EV still has losing months.",
    },
]
